const data = [
  {
    id: 0,
    name: "Dota timer",
    description: "alarm clock for a video game called DOTA2, that keeps the game in mind after completing your daily tasks",
    thumbnails: "Assets/dota-thumbnail.jpg",
    technologies: ["html", "css", "javascript"],
    live: "https://khaled-alkhateeb.github.io/Portfolio-Project/",
    source: "https://github.com/Khaled-AlKhateeb/dota-timer",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, ducimus aliquid excepturi sequi nemo neque quod officia pariatur cum, ea alias modi totam odio, odit doloribus. Assumenda eum facere sapiente distinctio ipsum fugiat sed animi perferendis obcaecati vitae labore maxime quos nisi, mollitia culpa perspiciatis! Sed reiciendis hic praesentium numquam.",
  },
  {
    id: 1,
    name: "Flappy bird clone",
    description: "a flappy bird game clone reactnative",
    thumbnails: "Assets/flappy-bird.jpg",
    technologies: ["html", "css", "javascript"],
    live: "https://khaled-alkhateeb.github.io/Portfolio-Project/",
    source: "https://github.com/Khaled-AlKhateeb/flappybird_clone",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, ducimus aliquid excepturi sequi nemo neque quod officia pariatur cum, ea alias modi totam odio, odit doloribus. Assumenda eum facere sapiente distinctio ipsum fugiat sed animi perferendis obcaecati vitae labore maxime quos nisi, mollitia culpa perspiciatis! Sed reiciendis hic praesentium numquam.",
  },
  {
    id: 2,
    name: "Webycob",
    description: "html/css website",
    thumbnails: "Assets/network_w_996.jpg",
    technologies: ["html", "css", "javascript"],
    live: "https://khaled-alkhateeb.github.io/Portfolio-Project/",
    source: "https://github.com/Khaled-AlKhateeb/Webycob",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, ducimus aliquid excepturi sequi nemo neque quod officia pariatur cum, ea alias modi totam odio, odit doloribus. Assumenda eum facere sapiente distinctio ipsum fugiat sed animi perferendis obcaecati vitae labore maxime quos nisi, mollitia culpa perspiciatis! Sed reiciendis hic praesentium numquam.",
  },
  {
    id: 3,
    name: "Sippar",
    description: "pharmaceutical factory website",
    thumbnails: "Assets/sippar.jpg",
    technologies: ["html", "css", "javascript"],
    live: "https://khaled-alkhateeb.github.io/Portfolio-Project/",
    source: "https://github.com/Khaled-AlKhateeb",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, ducimus aliquid excepturi sequi nemo neque quod officia pariatur cum, ea alias modi totam odio, odit doloribus. Assumenda eum facere sapiente distinctio ipsum fugiat sed animi perferendis obcaecati vitae labore maxime quos nisi, mollitia culpa perspiciatis! Sed reiciendis hic praesentium numquam.Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, ducimus aliquid excepturi sequi nemo neque quod officia pariatur cum, ea alias modi totam odio, odit doloribus. Assumenda eum facere sapiente distinctio ipsum fugiat sed animi perferendis obcaecati vitae labore maxime quos nisi, mollitia culpa perspiciatis! Sed reiciendis hic praesentium numquam.",
  },
  {
    id: 4,
    name: "Odin-tube",
    description: "A test clone for youtube",
    thumbnails: "Assets/thumbnail6.jpg",
    technologies: ["html", "css", "javascript"],
    live: "https://khaled-alkhateeb.github.io/Portfolio-Project/",
    source: "https://github.com/Khaled-AlKhateeb",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, ducimus aliquid excepturi sequi nemo neque quod officia pariatur cum, ea alias modi totam odio, odit doloribus. Assumenda eum facere sapiente distinctio ipsum fugiat sed animi perferendis obcaecati vitae labore maxime quos nisi, mollitia culpa perspiciatis! Sed reiciendis hic praesentium numquam.",
  },
  {
    id: 5,
    name: "Tic Tac Toe",
    description: "tic-tac-toe game made using reactnative",
    thumbnails: "Assets/tictactoe.jpeg",
    technologies: ["html", "css", "javascript"],
    live: "https://khaled-alkhateeb.github.io/Portfolio-Project/",
    source: "https://github.com/Khaled-AlKhateeb/tictactoe",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, ducimus aliquid excepturi sequi nemo neque quod officia pariatur cum, ea alias modi totam odio, odit doloribus. Assumenda eum facere sapiente distinctio ipsum fugiat sed animi perferendis obcaecati vitae labore maxime quos nisi, mollitia culpa perspiciatis! Sed reiciendis hic praesentium numquam.",
  },
  {
    id: 6,
    name: 'motortech',
    description: 'showeing the latest motor technologies',
    thumbnails: 'Assets/motortech-img1.png',
    technologies: ['html', 'css', 'javascript'],
    live: 'https://khaled-alkhateeb.github.io/motor-tech/index.html',
    source: 'https://github.com/Khaled-AlKhateeb/motor-tech',
    content: 'Technology served on Wheels, 2022 motor tech show brings you what is best for your wheels',
  }
]